package main

import (
	"context"
	"fmt"
	"os"

	"github.com/jackc/pgx/v5"
)

type product struct {
	ID    int32  `db:"id"`
	Name  string `db:"name"`
	Price int32  `db:"price"`
}

func main() {
	ctx := context.Background()

	conn, err := pgx.Connect(ctx, os.Getenv("DATABASE_URL"))
	if err != nil {
		fmt.Fprintf(os.Stderr, "Unable to connect to database: %v\n", err)
		os.Exit(1)
	}
	defer conn.Close(ctx)

	_, err = conn.Exec(ctx, `
create temporary table products (
	id int primary key generated by default as identity,
	name varchar(100) not null,
	price int not null
);

insert into products (name, price) values
	('Cheeseburger', 10),
	('Double Cheeseburger', 14),
	('Fries', 5),
	('Soft Drink', 3);
`)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Unable to setup example schema: %v\n", err)
		os.Exit(1)
	}

	rows, _ := conn.Query(ctx, "select id, name, price from products where price < $1 order by price desc", 12)
	products, err := pgx.CollectStructRows[product](rows)
	if err != nil {
		fmt.Fprintf(os.Stderr, "CollectStructRows error: %v\n", err)
		os.Exit(1)
	}

	for _, p := range products {
		fmt.Printf("%s: $%d\n", p.Name, p.Price)
	}
}
