package main

import (
	"context"
	"fmt"
	"os"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

type UserInfo struct {
	FirstName string `db:"first_name,omitempty"`
	LastName  string `db:"last_name"`
}

type User struct {
	ID int32
	UserInfo
	Email    pgtype.Text
	Age      *int32
	Metadata map[string]any
}

func main() {
	ctx := context.Background()
	conn, err := pgx.Connect(ctx, os.Getenv("DATABASE_URL"))
	if err != nil {
		fmt.Fprintf(os.Stderr, "Unable to connect to database: %v\n", err)
		os.Exit(1)
	}
	defer conn.Close(ctx)

	_, err = conn.Exec(ctx, `
		drop table if exists users;
		create temporary table users (
			id int primary key generated by default as identity,
			first_name text not null,
			last_name text not null,
			email text,
			age int,
			metadata jsonb
		);
		insert into users (first_name, last_name, email, age, metadata) values
			('John', 'Doe', 'john@example.com', 30, '{"role": "admin"}'::jsonb),
			('Jane', 'Smith', null, 25, null),
			('Bob', 'Johnson', 'bob@example.com', null, '{"role": "user"}'::jsonb);
	`)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Unable to setup test data: %v\n", err)
		os.Exit(1)
	}

	rows, _ := conn.Query(ctx, `
		SELECT ID, FIRST_NAME, last_name, EMAIL, AGE, metadata
		FROM users
		ORDER BY id
	`)
	users, err := pgx.RowsToStructs[User](rows)
	if err != nil {
		fmt.Fprintf(os.Stderr, "RowsToStructs failed: %v\n", err)
		os.Exit(1)
	}

	for i, u := range users {
		fmt.Printf("User %d: ID=%d, Name=%s %s", i+1, u.ID, u.FirstName, u.LastName)
		if u.Email.Valid {
			fmt.Printf(", Email=%s", u.Email.String)
		} else {
			fmt.Printf(", Email=<NULL>")
		}
		if u.Age != nil {
			fmt.Printf(", Age=%d", *u.Age)
		} else {
			fmt.Printf(", Age=<NULL>")
		}
		if u.Metadata != nil {
			fmt.Printf(", Metadata=%v", u.Metadata)
		} else {
			fmt.Printf(", Metadata=<NULL>")
		}
		fmt.Println()
	}
}
